name: flame
channels:
  - rdkit
  - defaults
dependencies:
  - cherrypy=14.0.1
  - numpy=1.14.0
  - matplotlib=2.1.2
  - pip=9.0.1
  - python=3.6.4
  - scipy=1.0.0
  - setuptools=38.4.0
  - scikit-learn=0.19.1
  - statsmodels=0.8.0
  - rdkit=2017.09.3.0
  - pyyaml
  - pip:
     - "https://github.com/phi-grib/standardiser/archive/master.zip"
     - "https://github.com/josecarlosgomezt/nonconformist/archive/master.zip"