admin_email: admin@domain.org
admin_name: Admin Name
config_status: true
homepage: homepage@domain.org
model_repository_path: E:\synced\internals\confomal_datasets\models
predictions_repository_path: E:\synced\internals\confomal_datasets\predictions
provider: My Organization
space_repository_path: E:\synced\internals\confomal_datasets\spaces
